import { notFound } from 'next/navigation';
import { PrintActions } from './PrintActions';
import { Clock } from 'lucide-react';
import { createAdminClient } from '@/lib/supabase/server.js';
import { safeDeserializeWeekPlan } from '@/utils/serialize';
import type { SerializedWeekPlan } from '@/utils/serialize';
import type { WeekPlan } from '@/lib/engine/types.js';

interface PageProps {
  params: Promise<{ planId: string }>;
}

const DAY_NAMES = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];

function formatDate(date: Date | string): string {
  const d = typeof date === 'string' ? new Date(date) : date;
  return d.toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric' });
}

function PrintPlan({ plan }: { plan: WeekPlan }) {
  return (
    <div className="max-w-3xl mx-auto px-6 py-8 font-sans text-sm">
      {/* Print header */}
      <div className="flex items-center justify-between border-b pb-4 mb-6">
        <div>
          <h1 className="text-2xl font-bold text-primary">TideeUp</h1>
          <p className="text-muted-foreground text-xs mt-0.5">Your weekly cleaning plan</p>
        </div>
        <div className="text-right text-xs text-muted-foreground">
          <p className="font-medium capitalize">{plan.metadata.season} plan</p>
          <p>{plan.metadata.totalTasksScheduled} tasks · ~{Math.round(plan.metadata.totalMinutesPlanned / 60)}h total</p>
        </div>
      </div>

      {/* Days */}
      <div className="space-y-6">
        {plan.days.map((day, i) => {
          if (day.tasks.length === 0) return null;
          const dateStr = formatDate(day.date);
          const featured = day.tasks.filter((t) => t.task.frequency !== 'daily');
          const stabilisers = day.tasks.filter((t) => t.task.frequency === 'daily');

          return (
            <div key={i} className="print-break-before">
              <div className="flex items-baseline justify-between mb-2 border-b border-dashed pb-1">
                <h2 className="font-bold text-base">{dateStr}</h2>
                <div className="flex items-center gap-1 text-xs text-muted-foreground">
                  <Clock className="w-3 h-3" />
                  <span>{day.totalMinutes} min</span>
                </div>
              </div>
              <ul className="space-y-1">
                {featured.map((t) => (
                  <li key={t.task.id} className="flex items-start gap-3">
                    <span className="mt-1 w-3.5 h-3.5 rounded border border-muted-foreground/40 shrink-0" />
                    <span className="flex-1">{t.task.title}</span>
                    <span className="text-muted-foreground text-xs shrink-0">{t.estimatedMinutes}m</span>
                  </li>
                ))}
                {stabilisers.length > 0 && (
                  <>
                    <li className="text-xs text-muted-foreground mt-2 mb-1 font-medium">Daily basics</li>
                    {stabilisers.map((t) => (
                      <li key={t.task.id} className="flex items-start gap-3">
                        <span className="mt-1 w-3.5 h-3.5 rounded border border-muted-foreground/40 shrink-0" />
                        <span className="flex-1 text-muted-foreground">{t.task.title}</span>
                        <span className="text-muted-foreground text-xs shrink-0">{t.estimatedMinutes}m</span>
                      </li>
                    ))}
                  </>
                )}
              </ul>
            </div>
          );
        })}
      </div>

      {/* Spillover */}
      {plan.spillover.length > 0 && (
        <div className="mt-8 border-t pt-4">
          <h3 className="font-semibold mb-2">Deferred to next week</h3>
          <ul className="space-y-1">
            {plan.spillover.map((t) => (
              <li key={t.id} className="text-muted-foreground">{t.title}</li>
            ))}
          </ul>
        </div>
      )}

      {/* Print footer */}
      <div className="mt-10 pt-4 border-t text-center text-xs text-muted-foreground">
        Generated by TideeUp · tideeup.com
      </div>
    </div>
  );
}

export default async function PrintPage({ params }: PageProps) {
  const { planId } = await params;

  let plan = null;
  try {
    const supabase = createAdminClient();
    const { data, error } = await supabase
      .from('plans')
      .select('week_plan')
      .eq('id', planId)
      .single();

    if (error || !data) notFound();
    plan = safeDeserializeWeekPlan(data.week_plan as SerializedWeekPlan);
    if (!plan) notFound();
  } catch {
    notFound();
  }

  return (
    <>
      <style>{`
        @media print {
          @page { margin: 1.5cm; }
          body { font-size: 10pt; }
        }
      `}</style>
      <PrintActions planId={planId} />
      <PrintPlan plan={plan} />
    </>
  );
}
