import type { Task } from '../engine/types.js';

/**
 * Canonical household task library — 78 tasks.
 *
 * Design notes:
 * - typicalMinutes: explicit active-work estimates per home size (S/M/L/XL).
 * - chaosImpact 0–1: how much pets/kids inflate this task's priority score.
 *   High = dishes, litter, bathroom basics (visible mess, health impact).
 *   Low  = dusting blinds, gutters, window washing (maintenance, less visible).
 * - fatigueCost 0–1: physical/mental weight for fatigue-smoothing across days.
 *   High = mopping large areas, deep oven clean, washing windows.
 *   Low  = wiping remotes, dryer lint trap, checking filters.
 * - flooringTypes / petTypes / homeTypes / seasonalMonths: null means "applies
 *   to all". Non-null filters to matching households only.
 */
export const TASK_LIBRARY: Task[] = [

  // ══════════════════════════════════════════════════════════════════════════
  // DAILY TASKS — universal
  // Target: high-priority stabilisers placed every day, capped at 60% of budget
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: 'dishes',
    title: 'Wash dishes / run dishwasher',
    zone: 'kitchen',
    frequency: 'daily',
    typicalMinutes: { S: 8, M: 10, L: 13, XL: 16 },
    chaosImpact: 0.55,
    fatigueCost: 0.20,
    tags: ['stabilizer'],
    kidsBoost: 5,
    petBoost: 2,
    flooringTypes: null,
    petTypes: null,
    seasonalMonths: null,
    homeTypes: null,
  },
  {
    id: 'wipe-kitchen-counters',
    title: 'Wipe kitchen counters and stovetop',
    zone: 'kitchen',
    frequency: 'daily',
    typicalMinutes: { S: 4, M: 5, L: 7, XL: 10 },
    chaosImpact: 0.45,
    fatigueCost: 0.10,
    tags: ['stabilizer', 'quick'],
    kidsBoost: 3,
    petBoost: 2,
    flooringTypes: null,
    petTypes: null,
    seasonalMonths: null,
    homeTypes: null,
  },
  {
    id: 'quick-bathroom-wipe',
    title: 'Quick bathroom wipe (sink and toilet)',
    zone: 'bathroom',
    frequency: 'daily',
    typicalMinutes: { S: 4, M: 5, L: 6, XL: 8 },
    chaosImpact: 0.40,
    fatigueCost: 0.10,
    tags: ['stabilizer', 'quick'],
    kidsBoost: 3,
    flooringTypes: null,
    petTypes: null,
    seasonalMonths: null,
    homeTypes: null,
  },
  {
    id: 'make-beds',
    title: 'Make beds',
    zone: 'bedroom',
    frequency: 'daily',
    typicalMinutes: { S: 5, M: 8, L: 12, XL: 15 },
    chaosImpact: 0.20,
    fatigueCost: 0.15,
    tags: ['stabilizer'],
    kidsBoost: 4,
    flooringTypes: null,
    petTypes: null,
    seasonalMonths: null,
    homeTypes: null,
  },
  {
    id: 'tidy-common-areas',
    title: 'Pick up and tidy common areas',
    zone: 'general',
    frequency: 'daily',
    typicalMinutes: { S: 5, M: 7, L: 10, XL: 12 },
    chaosImpact: 0.50,
    fatigueCost: 0.10,
    tags: ['stabilizer'],
    kidsBoost: 5,
    petBoost: 2,
    flooringTypes: null,
    petTypes: null,
    seasonalMonths: null,
    homeTypes: null,
  },
  {
    id: 'take-out-kitchen-trash',
    title: 'Take out kitchen trash if full',
    zone: 'general',
    frequency: 'daily',
    typicalMinutes: { S: 3, M: 4, L: 5, XL: 5 },
    chaosImpact: 0.35,
    fatigueCost: 0.08,
    tags: ['stabilizer', 'quick'],
    kidsBoost: 2,
    petBoost: 2,
    flooringTypes: null,
    petTypes: null,
    seasonalMonths: null,
    homeTypes: null,
  },
  {
    id: 'dryer-lint-trap',
    title: 'Clean dryer lint trap',
    zone: 'laundry',
    frequency: 'weekly',
    typicalMinutes: { S: 2, M: 2, L: 2, XL: 2 },
    chaosImpact: 0.05,
    fatigueCost: 0.03,
    tags: ['quick', 'maintenance'],
    flooringTypes: null,
    petTypes: null,
    seasonalMonths: null,
    homeTypes: null,
  },
  {
    id: 'sweep-high-traffic',
    title: 'Sweep high-traffic areas',
    zone: 'general',
    frequency: 'daily',
    typicalMinutes: { S: 5, M: 8, L: 11, XL: 14 },
    chaosImpact: 0.40,
    fatigueCost: 0.15,
    tags: ['stabilizer'],
    petBoost: 3,
    kidsBoost: 2,
    flooringTypes: ['hardwood', 'tile', 'mixed'],
    petTypes: null,
    seasonalMonths: null,
    homeTypes: null,
  },

  // ── Daily — pet-specific ───────────────────────────────────────────────────

  {
    id: 'cat-food-water-bowls',
    title: 'Wipe cat food and water bowls',
    zone: 'kitchen',
    frequency: 'daily',
    typicalMinutes: { S: 4, M: 5, L: 5, XL: 6 },
    chaosImpact: 0.10,
    fatigueCost: 0.05,
    tags: ['stabilizer', 'quick', 'pet'],
    flooringTypes: null,
    petTypes: ['cat-1-2', 'cat-3-plus'],
    seasonalMonths: null,
    homeTypes: null,
  },
  {
    id: 'litter-box-scoop',
    title: 'Scoop litter box',
    zone: 'bathroom',
    frequency: 'daily',
    typicalMinutes: { S: 4, M: 5, L: 6, XL: 7 },
    chaosImpact: 0.05,
    fatigueCost: 0.10,
    tags: ['stabilizer', 'quick', 'pet'],
    petBoost: 3,
    flooringTypes: null,
    petTypes: ['cat-1-2', 'cat-3-plus'],
    seasonalMonths: null,
    homeTypes: null,
  },
  {
    id: 'dog-water-bowl-refresh',
    title: 'Refresh dog water bowl',
    zone: 'kitchen',
    frequency: 'daily',
    typicalMinutes: { S: 3, M: 3, L: 4, XL: 4 },
    chaosImpact: 0.05,
    fatigueCost: 0.03,
    tags: ['stabilizer', 'quick', 'pet'],
    flooringTypes: null,
    petTypes: ['small-dog-1-2', 'large-dog-1-2', 'large-dog-3-plus'],
    seasonalMonths: null,
    homeTypes: null,
  },
  {
    id: 'mop-entry-after-walks',
    title: 'Wipe entry floor after dog walks',
    zone: 'general',
    frequency: 'daily',
    typicalMinutes: { S: 5, M: 6, L: 7, XL: 8 },
    chaosImpact: 0.20,
    fatigueCost: 0.10,
    tags: ['stabilizer', 'quick', 'pet'],
    flooringTypes: null,
    petTypes: ['large-dog-1-2', 'large-dog-3-plus'],
    seasonalMonths: [10, 11, 12, 1, 2, 3],
    homeTypes: null,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // WEEKLY TASKS — Kitchen
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: 'deep-clean-stovetop',
    title: 'Deep clean stovetop and burners',
    zone: 'kitchen',
    frequency: 'weekly',
    typicalMinutes: { S: 12, M: 18, L: 22, XL: 25 },
    chaosImpact: 0.60,
    fatigueCost: 0.35,
    tags: ['core'],
    kidsBoost: 5,
    petBoost: 3,
    flooringTypes: null,
    petTypes: null,
    seasonalMonths: null,
    homeTypes: null,
  },
  {
    id: 'clean-microwave',
    title: 'Clean microwave inside and out',
    zone: 'kitchen',
    frequency: 'weekly',
    typicalMinutes: { S: 7, M: 10, L: 12, XL: 12 },
    chaosImpact: 0.45,
    fatigueCost: 0.15,
    tags: ['quick'],
    kidsBoost: 3,
    flooringTypes: null,
    petTypes: null,
    seasonalMonths: null,
    homeTypes: null,
  },
  {
    id: 'wipe-cabinet-fronts',
    title: 'Wipe kitchen cabinet fronts',
    zone: 'kitchen',
    frequency: 'weekly',
    typicalMinutes: { S: 8, M: 13, L: 18, XL: 22 },
    chaosImpact: 0.30,
    fatigueCost: 0.20,
    tags: ['core'],
    kidsBoost: 5,
    petBoost: 2,
    flooringTypes: null,
    petTypes: null,
    seasonalMonths: null,
    homeTypes: null,
  },
  {
    id: 'clean-kitchen-sink',
    title: 'Scrub kitchen sink and faucet',
    zone: 'kitchen',
    frequency: 'weekly',
    typicalMinutes: { S: 6, M: 8, L: 10, XL: 10 },
    chaosImpact: 0.35,
    fatigueCost: 0.15,
    tags: ['core'],
    kidsBoost: 3,
    flooringTypes: null,
    petTypes: null,
    seasonalMonths: null,
    homeTypes: null,
  },
  {
    id: 'mop-kitchen-floor',
    title: 'Mop kitchen and dining floor',
    zone: 'kitchen',
    frequency: 'weekly',
    typicalMinutes: { S: 10, M: 15, L: 18, XL: 22 },
    chaosImpact: 0.50,
    fatigueCost: 0.40,
    tags: ['core'],
    kidsBoost: 5,
    petBoost: 5,
    flooringTypes: ['hardwood', 'tile', 'mixed'],
    petTypes: null,
    seasonalMonths: null,
    homeTypes: null,
  },
  {
    id: 'vacuum-kitchen-rug',
    title: 'Vacuum kitchen area rug',
    zone: 'kitchen',
    frequency: 'weekly',
    typicalMinutes: { S: 6, M: 8, L: 10, XL: 12 },
    chaosImpact: 0.30,
    fatigueCost: 0.20,
    tags: ['quick'],
    petBoost: 5,
    flooringTypes: ['carpet', 'mixed'],
    petTypes: null,
    seasonalMonths: null,
    homeTypes: null,
  },
  {
    id: 'empty-wipe-trash-can',
    title: 'Empty and wipe out kitchen trash can',
    zone: 'kitchen',
    frequency: 'weekly',
    typicalMinutes: { S: 6, M: 8, L: 10, XL: 10 },
    chaosImpact: 0.30,
    fatigueCost: 0.10,
    tags: ['quick'],
    kidsBoost: 3,
    petBoost: 2,
    flooringTypes: null,
    petTypes: null,
    seasonalMonths: null,
    homeTypes: null,
  },
  {
    id: 'wipe-fridge-exterior',
    title: 'Wipe refrigerator exterior and handles',
    zone: 'kitchen',
    frequency: 'monthly',
    typicalMinutes: { S: 4, M: 6, L: 7, XL: 8 },
    chaosImpact: 0.20,
    fatigueCost: 0.08,
    tags: ['quick'],
    kidsBoost: 2,
    flooringTypes: null,
    petTypes: null,
    seasonalMonths: null,
    homeTypes: null,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // WEEKLY TASKS — Bathroom
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: 'scrub-toilet',
    title: 'Scrub toilet bowl and wipe exterior',
    zone: 'bathroom',
    frequency: 'weekly',
    typicalMinutes: { S: 8, M: 12, L: 15, XL: 18 },
    chaosImpact: 0.35,
    fatigueCost: 0.30,
    tags: ['core'],
    kidsBoost: 5,
    flooringTypes: null,
    petTypes: null,
    seasonalMonths: null,
    homeTypes: null,
  },
  {
    id: 'clean-shower-tub',
    title: 'Scrub shower and tub surround',
    zone: 'bathroom',
    frequency: 'weekly',
    typicalMinutes: { S: 12, M: 18, L: 22, XL: 26 },
    chaosImpact: 0.30,
    fatigueCost: 0.45,
    tags: ['core'],
    kidsBoost: 5,
    flooringTypes: null,
    petTypes: null,
    seasonalMonths: null,
    homeTypes: null,
  },
  {
    id: 'scrub-bathroom-sink',
    title: 'Scrub bathroom sink and faucet',
    zone: 'bathroom',
    frequency: 'weekly',
    typicalMinutes: { S: 6, M: 9, L: 11, XL: 12 },
    chaosImpact: 0.25,
    fatigueCost: 0.20,
    tags: ['core'],
    kidsBoost: 3,
    flooringTypes: null,
    petTypes: null,
    seasonalMonths: null,
    homeTypes: null,
  },
  {
    id: 'mop-bathroom-floor',
    title: 'Mop bathroom floor',
    zone: 'bathroom',
    frequency: 'weekly',
    typicalMinutes: { S: 6, M: 8, L: 10, XL: 12 },
    chaosImpact: 0.25,
    fatigueCost: 0.25,
    tags: ['core'],
    kidsBoost: 3,
    flooringTypes: ['tile', 'mixed'],
    petTypes: null,
    seasonalMonths: null,
    homeTypes: null,
  },
  {
    id: 'wipe-bathroom-hardwood-floor',
    title: 'Wipe and spot-clean bathroom floor',
    zone: 'bathroom',
    frequency: 'weekly',
    typicalMinutes: { S: 5, M: 7, L: 8, XL: 10 },
    chaosImpact: 0.20,
    fatigueCost: 0.15,
    tags: ['quick'],
    flooringTypes: ['hardwood'],
    petTypes: null,
    seasonalMonths: null,
    homeTypes: null,
  },
  {
    id: 'replace-towels-bathmat',
    title: 'Replace towels and bath mat',
    zone: 'bathroom',
    frequency: 'weekly',
    typicalMinutes: { S: 4, M: 5, L: 5, XL: 6 },
    chaosImpact: 0.10,
    fatigueCost: 0.05,
    tags: ['quick'],
    flooringTypes: null,
    petTypes: null,
    seasonalMonths: null,
    homeTypes: null,
  },
  {
    id: 'clean-bathroom-mirror',
    title: 'Clean bathroom mirror',
    zone: 'bathroom',
    frequency: 'monthly',
    typicalMinutes: { S: 4, M: 5, L: 5, XL: 6 },
    chaosImpact: 0.10,
    fatigueCost: 0.05,
    tags: ['quick'],
    kidsBoost: 2,
    flooringTypes: null,
    petTypes: null,
    seasonalMonths: null,
    homeTypes: null,
  },
  {
    id: 'restock-toiletries',
    title: 'Restock toiletries and check supplies',
    zone: 'bathroom',
    frequency: 'monthly',
    typicalMinutes: { S: 2, M: 3, L: 4, XL: 5 },
    chaosImpact: 0.10,
    fatigueCost: 0.03,
    tags: ['quick'],
    flooringTypes: null,
    petTypes: null,
    seasonalMonths: null,
    homeTypes: null,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // WEEKLY TASKS — Bedroom
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: 'change-bed-sheets',
    title: 'Change bed sheets',
    zone: 'bedroom',
    frequency: 'weekly',
    typicalMinutes: { S: 8, M: 13, L: 16, XL: 20 },
    chaosImpact: 0.20,
    fatigueCost: 0.30,
    tags: ['core'],
    kidsBoost: 5,
    flooringTypes: null,
    petTypes: null,
    seasonalMonths: null,
    homeTypes: null,
  },
  {
    id: 'vacuum-carpet-bedroom',
    title: 'Vacuum bedroom carpet',
    zone: 'bedroom',
    frequency: 'weekly',
    typicalMinutes: { S: 8, M: 12, L: 15, XL: 18 },
    chaosImpact: 0.35,
    fatigueCost: 0.30,
    tags: ['core'],
    petBoost: 8,
    kidsBoost: 3,
    flooringTypes: ['carpet', 'mixed'],
    petTypes: null,
    seasonalMonths: null,
    homeTypes: null,
  },
  {
    id: 'sweep-hardwood-bedroom',
    title: 'Sweep and dust hardwood bedroom floor',
    zone: 'bedroom',
    frequency: 'weekly',
    typicalMinutes: { S: 6, M: 10, L: 12, XL: 15 },
    chaosImpact: 0.25,
    fatigueCost: 0.20,
    tags: ['core'],
    petBoost: 5,
    flooringTypes: ['hardwood'],
    petTypes: null,
    seasonalMonths: null,
    homeTypes: null,
  },
  {
    id: 'dust-bedroom-surfaces',
    title: 'Dust bedroom surfaces and ceiling fan',
    zone: 'bedroom',
    frequency: 'weekly',
    typicalMinutes: { S: 8, M: 12, L: 15, XL: 18 },
    chaosImpact: 0.20,
    fatigueCost: 0.20,
    tags: ['core'],
    petBoost: 5,
    flooringTypes: null,
    petTypes: null,
    seasonalMonths: null,
    homeTypes: null,
  },
  {
    id: 'declutter-bedroom-surfaces',
    title: 'Declutter and tidy bedroom surfaces',
    zone: 'bedroom',
    frequency: 'weekly',
    typicalMinutes: { S: 8, M: 10, L: 13, XL: 15 },
    chaosImpact: 0.30,
    fatigueCost: 0.20,
    tags: ['core'],
    kidsBoost: 8,
    flooringTypes: null,
    petTypes: null,
    seasonalMonths: null,
    homeTypes: null,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // WEEKLY TASKS — Living areas
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: 'vacuum-carpet-living',
    title: 'Vacuum living area carpet',
    zone: 'living',
    frequency: 'weekly',
    typicalMinutes: { S: 12, M: 20, L: 25, XL: 30 },
    chaosImpact: 0.60,
    fatigueCost: 0.40,
    tags: ['core'],
    petBoost: 10,
    kidsBoost: 5,
    flooringTypes: ['carpet', 'mixed'],
    petTypes: null,
    seasonalMonths: null,
    homeTypes: null,
  },
  {
    id: 'sweep-hardwood-living',
    title: 'Sweep hardwood living area floors',
    zone: 'living',
    frequency: 'weekly',
    typicalMinutes: { S: 8, M: 14, L: 18, XL: 22 },
    chaosImpact: 0.45,
    fatigueCost: 0.25,
    tags: ['core'],
    petBoost: 5,
    flooringTypes: ['hardwood'],
    petTypes: null,
    seasonalMonths: null,
    homeTypes: null,
  },
  {
    id: 'mop-hardwood-living',
    title: 'Mop hardwood living area floors',
    zone: 'living',
    frequency: 'weekly',
    typicalMinutes: { S: 12, M: 18, L: 22, XL: 28 },
    chaosImpact: 0.45,
    fatigueCost: 0.50,
    tags: ['core'],
    petBoost: 5,
    flooringTypes: ['hardwood'],
    petTypes: null,
    seasonalMonths: null,
    homeTypes: null,
  },
  {
    id: 'dust-furniture-surfaces',
    title: 'Dust furniture and surfaces',
    zone: 'living',
    frequency: 'weekly',
    typicalMinutes: { S: 12, M: 15, L: 20, XL: 22 },
    chaosImpact: 0.25,
    fatigueCost: 0.20,
    tags: ['core'],
    petBoost: 5,
    flooringTypes: null,
    petTypes: null,
    seasonalMonths: null,
    homeTypes: null,
  },
  {
    id: 'wipe-electronics-remotes',
    title: 'Wipe down electronics and remotes',
    zone: 'living',
    frequency: 'monthly',
    typicalMinutes: { S: 5, M: 6, L: 7, XL: 8 },
    chaosImpact: 0.10,
    fatigueCost: 0.05,
    tags: ['quick'],
    kidsBoost: 2,
    flooringTypes: null,
    petTypes: null,
    seasonalMonths: null,
    homeTypes: null,
  },
  {
    id: 'vacuum-upholstered-furniture',
    title: 'Vacuum upholstered furniture',
    zone: 'living',
    frequency: 'weekly',
    typicalMinutes: { S: 12, M: 16, L: 20, XL: 22 },
    chaosImpact: 0.40,
    fatigueCost: 0.30,
    tags: ['core'],
    petBoost: 10,
    kidsBoost: 5,
    flooringTypes: null,
    petTypes: null,
    seasonalMonths: null,
    homeTypes: null,
  },

  // ── Weekly — General ───────────────────────────────────────────────────────

  {
    id: 'tidy-entryway',
    title: 'Tidy entryway and mudroom',
    zone: 'general',
    frequency: 'weekly',
    typicalMinutes: { S: 6, M: 8, L: 10, XL: 12 },
    chaosImpact: 0.50,
    fatigueCost: 0.12,
    tags: ['quick'],
    kidsBoost: 5,
    petBoost: 3,
    flooringTypes: null,
    petTypes: null,
    seasonalMonths: null,
    homeTypes: null,
  },
  {
    id: 'empty-all-waste-bins',
    title: 'Empty all waste bins throughout home',
    zone: 'general',
    frequency: 'weekly',
    typicalMinutes: { S: 6, M: 8, L: 10, XL: 12 },
    chaosImpact: 0.30,
    fatigueCost: 0.10,
    tags: ['quick'],
    kidsBoost: 3,
    petBoost: 2,
    flooringTypes: null,
    petTypes: null,
    seasonalMonths: null,
    homeTypes: null,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // WEEKLY TASKS — Laundry
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: 'laundry-wash-dry',
    title: 'Run laundry (wash + dry)',
    zone: 'laundry',
    frequency: 'weekly',
    typicalMinutes: { S: 10, M: 12, L: 15, XL: 20 },
    chaosImpact: 0.50,
    fatigueCost: 0.15,
    tags: ['core'],
    kidsBoost: 10,
    petBoost: 5,
    flooringTypes: null,
    petTypes: null,
    seasonalMonths: null,
    homeTypes: null,
  },
  {
    id: 'laundry-fold-put-away',
    title: 'Fold and put away laundry',
    zone: 'laundry',
    frequency: 'weekly',
    typicalMinutes: { S: 15, M: 22, L: 28, XL: 35 },
    chaosImpact: 0.40,
    fatigueCost: 0.25,
    tags: ['core'],
    kidsBoost: 10,
    flooringTypes: null,
    petTypes: null,
    seasonalMonths: null,
    homeTypes: null,
  },
  {
    id: 'wash-bed-sheets',
    title: 'Wash bed sheets (active time)',
    zone: 'laundry',
    frequency: 'weekly',
    typicalMinutes: { S: 10, M: 12, L: 15, XL: 18 },
    chaosImpact: 0.15,
    fatigueCost: 0.10,
    tags: ['core'],
    flooringTypes: null,
    petTypes: null,
    seasonalMonths: null,
    homeTypes: null,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // WEEKLY TASKS — Pet-specific
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: 'litter-box-full-clean',
    title: 'Full litter box clean and refill',
    zone: 'general',
    frequency: 'weekly',
    typicalMinutes: { S: 14, M: 16, L: 18, XL: 20 },
    chaosImpact: 0.10,
    fatigueCost: 0.30,
    tags: ['pet'],
    petBoost: 5,
    flooringTypes: null,
    petTypes: ['cat-1-2', 'cat-3-plus'],
    seasonalMonths: null,
    homeTypes: null,
  },
  {
    id: 'vacuum-cat-hair-furniture',
    title: 'Vacuum cat hair from furniture and surfaces',
    zone: 'living',
    frequency: 'weekly',
    typicalMinutes: { S: 8, M: 12, L: 15, XL: 18 },
    chaosImpact: 0.15,
    fatigueCost: 0.25,
    tags: ['pet'],
    petBoost: 5,
    flooringTypes: null,
    petTypes: ['cat-1-2', 'cat-3-plus'],
    seasonalMonths: null,
    homeTypes: null,
  },
  {
    id: 'dog-feeding-area-clean',
    title: 'Clean dog bowls and feeding area',
    zone: 'kitchen',
    frequency: 'weekly',
    typicalMinutes: { S: 6, M: 8, L: 10, XL: 10 },
    chaosImpact: 0.20,
    fatigueCost: 0.12,
    tags: ['pet'],
    petBoost: 5,
    flooringTypes: null,
    petTypes: ['small-dog-1-2', 'large-dog-1-2', 'large-dog-3-plus'],
    seasonalMonths: null,
    homeTypes: null,
  },
  {
    id: 'vacuum-dog-hair-furniture',
    title: 'Vacuum dog hair from furniture and surfaces',
    zone: 'living',
    frequency: 'weekly',
    typicalMinutes: { S: 8, M: 12, L: 16, XL: 20 },
    chaosImpact: 0.20,
    fatigueCost: 0.28,
    tags: ['pet'],
    petBoost: 8,
    flooringTypes: null,
    petTypes: ['small-dog-1-2', 'large-dog-1-2', 'large-dog-3-plus'],
    seasonalMonths: null,
    homeTypes: null,
  },
  {
    id: 'small-animal-cage-clean',
    title: 'Clean cage or tank (small animals)',
    zone: 'general',
    frequency: 'weekly',
    typicalMinutes: { S: 25, M: 25, L: 25, XL: 25 },
    chaosImpact: 0.10,
    fatigueCost: 0.40,
    tags: ['pet'],
    flooringTypes: null,
    petTypes: ['small-animals', 'other'],
    seasonalMonths: null,
    homeTypes: null,
  },
  {
    id: 'wipe-cage-area-surfaces',
    title: 'Wipe surfaces around cage or tank',
    zone: 'general',
    frequency: 'weekly',
    typicalMinutes: { S: 7, M: 9, L: 10, XL: 12 },
    chaosImpact: 0.10,
    fatigueCost: 0.12,
    tags: ['pet', 'quick'],
    flooringTypes: null,
    petTypes: ['small-animals', 'other'],
    seasonalMonths: null,
    homeTypes: null,
  },

  // ══════════════════════════════════════════════════════════════════════════
  // WEEKLY TASKS — Outdoor
  // (townhouse, single-family, large-home only)
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: 'sweep-porch-entry',
    title: 'Sweep porch and entry path',
    zone: 'outdoor',
    frequency: 'weekly',
    typicalMinutes: { S: 8, M: 10, L: 12, XL: 15 },
    chaosImpact: 0.20,
    fatigueCost: 0.15,
    tags: ['outdoor'],
    petBoost: 3,
    flooringTypes: null,
    petTypes: null,
    seasonalMonths: null,
    homeTypes: ['townhouse', 'single-family', 'large-home'],
  },
  {
    id: 'mow-lawn',
    title: 'Mow lawn',
    zone: 'outdoor',
    frequency: 'weekly',
    typicalMinutes: { S: 20, M: 35, L: 45, XL: 60 },
    chaosImpact: 0.10,
    fatigueCost: 0.60,
    tags: ['outdoor'],
    flooringTypes: null,
    petTypes: null,
    seasonalMonths: [4, 5, 6, 7, 8, 9, 10],
    homeTypes: ['single-family', 'large-home'],
  },
  {
    id: 'water-plants-garden',
    title: 'Water plants and garden',
    zone: 'outdoor',
    frequency: 'weekly',
    typicalMinutes: { S: 8, M: 12, L: 18, XL: 22 },
    chaosImpact: 0.10,
    fatigueCost: 0.15,
    tags: ['outdoor'],
    flooringTypes: null,
    petTypes: null,
    seasonalMonths: [4, 5, 6, 7, 8, 9],
    homeTypes: ['townhouse', 'single-family', 'large-home'],
  },

  // ══════════════════════════════════════════════════════════════════════════
  // MONTHLY TASKS — Kitchen
  // ══════════════════════════════════════════════════════════════════════════

  {
    id: 'deep-clean-oven',
    title: 'Deep clean oven',
    zone: 'kitchen',
    frequency: 'monthly',
    typicalMinutes: { S: 35, M: 45, L: 55, XL: 60 },
    chaosImpact: 0.50,
    fatigueCost: 0.70,
    tags: ['deep'],
    kidsBoost: 10,
    flooringTypes: null,
    petTypes: null,
    seasonalMonths: null,
    homeTypes: null,
  },
  {
    id: 'clean-fridge-interior',
    title: 'Clean refrigerator interior',
    zone: 'kitchen',
    frequency: 'monthly',
    typicalMinutes: { S: 22, M: 30, L: 38, XL: 45 },
    chaosImpact: 0.35,
    fatigueCost: 0.50,
    tags: ['deep'],
    kidsBoost: 5,
    flooringTypes: null,
    petTypes: null,
    seasonalMonths: null,
    homeTypes: null,
  },
  {
    id: 'descale-coffee-maker',
    title: 'Descale coffee maker',
    zone: 'kitchen',
    frequency: 'monthly',
    typicalMinutes: { S: 15, M: 15, L: 15, XL: 15 },
    chaosImpact: 0.05,
    fatigueCost: 0.10,
    tags: ['maintenance', 'quick'],
    flooringTypes: null,
    petTypes: null,
    seasonalMonths: null,
    homeTypes: null,
  },
  {
    id: 'organize-pantry',
    title: 'Organise pantry and check expiry dates',
    zone: 'kitchen',
    frequency: 'monthly',
    typicalMinutes: { S: 20, M: 28, L: 35, XL: 40 },
    chaosImpact: 0.30,
    fatigueCost: 0.30,
    tags: ['deep', 'organize'],
    kidsBoost: 5,
    flooringTypes: null,
    petTypes: null,
    seasonalMonths: null,
    homeTypes: null,
  },

  // ── Monthly — Bathroom ────────────────────────────────────────────────────

  {
    id: 'clean-bathroom-grout',
    title: 'Scrub tile grout',
    zone: 'bathroom',
    frequency: 'monthly',
    typicalMinutes: { S: 20, M: 28, L: 35, XL: 40 },
    chaosImpact: 0.15,
    fatigueCost: 0.65,
    tags: ['deep'],
    flooringTypes: ['tile'],
    petTypes: null,
    seasonalMonths: null,
    homeTypes: null,
  },

  // ── Monthly — Bedroom ─────────────────────────────────────────────────────

  {
    id: 'clean-under-bed',
    title: 'Clean under bed (vacuum or sweep)',
    zone: 'bedroom',
    frequency: 'monthly',
    typicalMinutes: { S: 12, M: 16, L: 20, XL: 24 },
    chaosImpact: 0.25,
    fatigueCost: 0.40,
    tags: ['deep'],
    petBoost: 8,
    flooringTypes: null,
    petTypes: null,
    seasonalMonths: null,
    homeTypes: null,
  },

  // ── Monthly — Living ──────────────────────────────────────────────────────

  {
    id: 'wash-windows-interior',
    title: 'Wash interior windows and sills',
    zone: 'living',
    frequency: 'monthly',
    typicalMinutes: { S: 18, M: 25, L: 32, XL: 40 },
    chaosImpact: 0.15,
    fatigueCost: 0.45,
    tags: ['deep'],
    kidsBoost: 5,
    flooringTypes: null,
    petTypes: null,
    seasonalMonths: null,
    homeTypes: null,
  },

  // ── Monthly — General ─────────────────────────────────────────────────────

  {
    id: 'wipe-light-switches-handles',
    title: 'Wipe all light switches and door handles',
    zone: 'general',
    frequency: 'monthly',
    typicalMinutes: { S: 8, M: 12, L: 15, XL: 18 },
    chaosImpact: 0.30,
    fatigueCost: 0.15,
    tags: ['health'],
    kidsBoost: 5,
    petBoost: 3,
    flooringTypes: null,
    petTypes: null,
    seasonalMonths: null,
    homeTypes: null,
  },
  {
    id: 'clean-window-tracks',
    title: 'Clean window tracks and frames',
    zone: 'general',
    frequency: 'monthly',
    typicalMinutes: { S: 12, M: 16, L: 20, XL: 25 },
    chaosImpact: 0.10,
    fatigueCost: 0.30,
    tags: ['deep'],
    flooringTypes: null,
    petTypes: null,
    seasonalMonths: null,
    homeTypes: null,
  },
  {
    id: 'dust-blinds-curtains',
    title: 'Dust blinds and curtains',
    zone: 'general',
    frequency: 'monthly',
    typicalMinutes: { S: 15, M: 22, L: 28, XL: 35 },
    chaosImpact: 0.10,
    fatigueCost: 0.30,
    tags: ['deep'],
    petBoost: 5,
    flooringTypes: null,
    petTypes: null,
    seasonalMonths: null,
    homeTypes: null,
  },
  {
    // Quarterly — February, May, August, November
    id: 'check-replace-air-filters',
    title: 'Check and replace air filters',
    zone: 'general',
    frequency: 'monthly',
    typicalMinutes: { S: 8, M: 12, L: 15, XL: 18 },
    chaosImpact: 0.05,
    fatigueCost: 0.10,
    tags: ['maintenance'],
    petBoost: 3,
    flooringTypes: null,
    petTypes: null,
    seasonalMonths: [2, 5, 8, 11],
    homeTypes: null,
  },
  {
    // Quarterly — January, April, July, October
    id: 'deep-clean-baseboards',
    title: 'Deep clean baseboards and trim',
    zone: 'general',
    frequency: 'monthly',
    typicalMinutes: { S: 22, M: 30, L: 38, XL: 45 },
    chaosImpact: 0.15,
    fatigueCost: 0.55,
    tags: ['deep'],
    petBoost: 5,
    flooringTypes: null,
    petTypes: null,
    seasonalMonths: [1, 4, 7, 10],
    homeTypes: null,
  },
  {
    // Quarterly — February, May, August, November
    id: 'clean-ceiling-fans',
    title: 'Clean ceiling fans',
    zone: 'general',
    frequency: 'monthly',
    typicalMinutes: { S: 12, M: 16, L: 20, XL: 22 },
    chaosImpact: 0.08,
    fatigueCost: 0.30,
    tags: ['deep'],
    flooringTypes: null,
    petTypes: null,
    seasonalMonths: [2, 5, 8, 11],
    homeTypes: null,
  },
  {
    id: 'vacuum-under-behind-furniture',
    title: 'Vacuum under and behind furniture',
    zone: 'general',
    frequency: 'monthly',
    typicalMinutes: { S: 15, M: 22, L: 28, XL: 35 },
    chaosImpact: 0.35,
    fatigueCost: 0.55,
    tags: ['deep'],
    petBoost: 10,
    kidsBoost: 5,
    flooringTypes: null,
    petTypes: null,
    seasonalMonths: null,
    homeTypes: null,
  },

  // ── Monthly — Laundry ─────────────────────────────────────────────────────

  {
    id: 'clean-washing-machine-drum',
    title: 'Deep clean washing machine (drum, seal & filter)',
    zone: 'laundry',
    frequency: 'monthly',
    typicalMinutes: { S: 12, M: 15, L: 18, XL: 20 },
    chaosImpact: 0.10,
    fatigueCost: 0.15,
    tags: ['maintenance'],
    kidsBoost: 3,
    flooringTypes: null,
    petTypes: null,
    seasonalMonths: null,
    homeTypes: null,
  },
  {
    id: 'wipe-washer-door-seal',
    title: 'Quick wipe washer door seal & gasket',
    zone: 'laundry',
    frequency: 'monthly',
    typicalMinutes: { S: 7, M: 9, L: 10, XL: 12 },
    chaosImpact: 0.05,
    fatigueCost: 0.08,
    tags: ['maintenance', 'quick'],
    flooringTypes: null,
    petTypes: null,
    seasonalMonths: null,
    homeTypes: null,
  },

  // ── Monthly — Pet-specific ────────────────────────────────────────────────

  {
    id: 'wipe-cat-tree-scratcher',
    title: 'Wipe down cat tree and scratching posts',
    zone: 'general',
    frequency: 'monthly',
    typicalMinutes: { S: 7, M: 9, L: 10, XL: 10 },
    chaosImpact: 0.05,
    fatigueCost: 0.12,
    tags: ['pet'],
    flooringTypes: null,
    petTypes: ['cat-1-2', 'cat-3-plus'],
    seasonalMonths: null,
    homeTypes: null,
  },
  {
    id: 'wash-dog-bedding-small',
    title: 'Wash dog bedding',
    zone: 'laundry',
    frequency: 'monthly',
    typicalMinutes: { S: 18, M: 22, L: 25, XL: 28 },
    chaosImpact: 0.05,
    fatigueCost: 0.15,
    tags: ['pet'],
    flooringTypes: null,
    petTypes: ['small-dog-1-2'],
    seasonalMonths: null,
    homeTypes: null,
  },
  {
    id: 'wash-dog-bedding-large',
    title: 'Wash large dog bedding',
    zone: 'laundry',
    frequency: 'monthly',
    typicalMinutes: { S: 25, M: 32, L: 38, XL: 45 },
    chaosImpact: 0.05,
    fatigueCost: 0.20,
    tags: ['pet'],
    flooringTypes: null,
    petTypes: ['large-dog-1-2', 'large-dog-3-plus'],
    seasonalMonths: null,
    homeTypes: null,
  },
  {
    id: 'wipe-dog-crate',
    title: 'Wipe down dog crate and bedding area',
    zone: 'general',
    frequency: 'monthly',
    typicalMinutes: { S: 8, M: 10, L: 12, XL: 12 },
    chaosImpact: 0.05,
    fatigueCost: 0.15,
    tags: ['pet'],
    flooringTypes: null,
    petTypes: ['small-dog-1-2', 'large-dog-1-2', 'large-dog-3-plus'],
    seasonalMonths: null,
    homeTypes: null,
  },

  // ── Monthly — Outdoor ─────────────────────────────────────────────────────

  {
    id: 'rake-leaves',
    title: 'Rake and bag leaves',
    zone: 'outdoor',
    frequency: 'monthly',
    typicalMinutes: { S: 22, M: 35, L: 48, XL: 60 },
    chaosImpact: 0.10,
    fatigueCost: 0.60,
    tags: ['outdoor', 'deep'],
    flooringTypes: null,
    petTypes: null,
    seasonalMonths: [10, 11, 12],
    homeTypes: ['townhouse', 'single-family', 'large-home'],
  },
  {
    id: 'clean-outdoor-furniture',
    title: 'Clean outdoor furniture',
    zone: 'outdoor',
    frequency: 'monthly',
    typicalMinutes: { S: 15, M: 22, L: 28, XL: 35 },
    chaosImpact: 0.10,
    fatigueCost: 0.35,
    tags: ['outdoor'],
    flooringTypes: null,
    petTypes: null,
    seasonalMonths: [5, 9],
    homeTypes: ['townhouse', 'single-family', 'large-home'],
  },
  {
    id: 'clean-gutters',
    title: 'Clean gutters and downspouts',
    zone: 'outdoor',
    frequency: 'monthly',
    typicalMinutes: { S: 35, M: 45, L: 55, XL: 65 },
    chaosImpact: 0.05,
    fatigueCost: 0.70,
    tags: ['outdoor', 'deep', 'maintenance'],
    flooringTypes: null,
    petTypes: null,
    seasonalMonths: [4, 10],
    homeTypes: ['single-family', 'large-home'],
  },
  {
    id: 'wash-windows-exterior',
    title: 'Wash exterior windows',
    zone: 'outdoor',
    frequency: 'monthly',
    typicalMinutes: { S: 35, M: 45, L: 55, XL: 65 },
    chaosImpact: 0.05,
    fatigueCost: 0.60,
    tags: ['outdoor', 'deep'],
    flooringTypes: null,
    petTypes: null,
    seasonalMonths: [5, 9],
    homeTypes: ['single-family', 'large-home'],
  },
  {
    id: 'wipe-entry-door-hardware',
    title: 'Wipe entry door and hardware',
    zone: 'outdoor',
    frequency: 'monthly',
    typicalMinutes: { S: 5, M: 6, L: 7, XL: 8 },
    chaosImpact: 0.10,
    fatigueCost: 0.05,
    tags: ['quick', 'outdoor'],
    flooringTypes: null,
    petTypes: null,
    seasonalMonths: null,
    homeTypes: ['townhouse', 'single-family', 'large-home'],
  },
];

/** Convenience lookup by id */
export function getTaskById(id: string): Task | undefined {
  return TASK_LIBRARY.find((t) => t.id === id);
}
